aa: rand-m9-mstd0.5
amp: true
aug_splits: 0
aux_weight: 0
batch_size: 256
bn_eps: 0.001
bn_momentum: 0.1
bn_tf: false
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
data: /userhome/temp_data/ImageNet
decay_epochs: 2.4
decay_rate: 0.97
dist_bn: ''
drop: 0.2
drop_connect: 0.2
epochs: 450
eval_metric: prec1
genotype: null
gp: avg
img_size: null
init_channels: 48
initial_checkpoint: ''
interpolation: ''
jsd: false
layers: 14
local_rank: 0
log_interval: 50
lr: 0.016
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_off_epoch: 0
model: resnet101
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
model_init: he_fout
model_method: my_model_collection
model_name: dynamic_SNG_V3_ofa_imagenet_width_multi_1.3_400_B
momentum: 0.9
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_gpu: 1
opt: rmsproptf
opt_eps: 0.001
output: /userhome/project/pytorch_image_classification/experiments/timm_train
pin_mem: false
pretrained: false
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.2
resplit: false
resume: ''
save_images: false
sched: step
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
structure_path: /userhome/model_zoo/dynamic_SNG_V3_ofa_imagenet_width_multi_1.3_400_B.json
sync_bn: false
train_interpolation: random
tta: 0
validation_batch_size_multiplier: 1
warmup_epochs: 3
warmup_lr: 1.0e-06
weight_decay: 1.0e-05
workers: 16
